### PR TITLE
Add juju-login cmd to enable re-login to controller

### PR DESCRIPTION
**Pull request by gboutry**
Add utils group with subcommand juju-login. The juju-login command will re-login to controller with the user of the current node.

Fixes LP#2028139

### CODE REVIEW

**Comment by hemanthnakkina** [comment]
Just a thought, do we want to consolidate some of the commands under utils group?

generate-preseed
openrc
cloud-config
launch

I am tempted to put `prepare-node-script` as well but given its usage at the start for every node, should be ok to be in the main command  group

**Comment by hemanthnakkina** [comment]
> fix: #LP-2028139

Maybe we should start following single notation for bug number in commit message, what do you think about
`Fixes LP#2028139`

**Comment by gboutry** [comment]
> > fix: #LP-2028139
> 
> Maybe we should start following single notation for bug number in commit message, what do you think about `Fixes LP#2028139`

I couldn't remember the right way, thanks

**Comment by gboutry** [comment]
> Just a thought, do we want to consolidate some of the commands under utils group?
> 
> generate-preseed openrc cloud-config launch
> 
> I am tempted to put `prepare-node-script` as well but given its usage at the start for every node, should be ok to be in the main command group

I'm not sure, juju login is really an utility to connect to juju, and in a normal operation, users should not use juju.

While the commands `generate-preseed`, `openrc`, `cloud-config`, `launch` are meant to be used in normal operation

**Pull request closed without merging**
