### PR TITLE
Embed microcluster into snap-openstack repository

### PR DESCRIPTION
**Pull request by gboutry**
Embeds Microcluster into snap-openstack.

Github workflows updated to be able to run on python or golang files as needed.

### CODE REVIEW

**Review by hemanthnakkina — COMMENTED** [review]
I think it will be more clean if all the sunbeam python code (including tests, requirements.txt, tox.ini if not shared with microcluster) also goes into a single folder just like how microcluster has all go related pieces.

**Comment by gboutry** [comment]
@hemanthnakkina are you OK with `openstack` for the python related stuff ? Since we're in `snap-openstack`.
I would find it weird to call it `python` since microcluster is not `golang`. And I don't want to call microcluster golang.

**Review by hemanthnakkina — APPROVED** [review]
LGTM, lets wait for the folder name for python code on what others think.

**Comment by javacruft** [comment]
I'm not sure about the use `microcluster` for the sunbeamd codebase as that's exactly the same name as the microcluster library we're based on - can we use `sunbeam-microcluster` (following the standalone repo name) so that we're indicating its' specialised?  Also do we need to update the internal imports which currently reference `openstack-snaps/sunbeam-microcluster`?

On the name of the `apps` folder - again feels a bit anonymous - how about `sunbeam-snap` or `sunbeam-python` or maybe even just `sunbeam`?

**Comment by gboutry** [comment]
> I'm not sure about the use `microcluster` for the sunbeamd codebase as that's exactly the same name as the microcluster library we're based on - can we use `sunbeam-microcluster` (following the standalone repo name) so that we're indicating its' specialised? Also do we need to update the internal imports which currently reference `openstack-snaps/sunbeam-microcluster`?
> 
> On the name of the `apps` folder - again feels a bit anonymous - how about `sunbeam-snap` or `sunbeam-python` or maybe even just `sunbeam`?

Ok, I renamed microcluster to sunbeam-microcluster, and apps to sunbeam-python.

Also resolved the internal imports issue

**Pull request merged**
