### PR TITLE
Add COS Lite plugin

### PR DESCRIPTION
**Pull request by hemanthnakkina**
Add COS Lite plugin with terraform plans in this repo.

### CODE REVIEW

**Review by gboutry — APPROVED** [review]

**Review by gboutry — CHANGES_REQUESTED** [review]
Could you add a command to get the dashboard urls like we do for horizon ?

**Comment by hemanthnakkina** [comment]
> Could you add a command to get the dashboard urls like we do for horizon ?

Good suggestion, this requires expose of dashboard url from grafana-k8s-operator.
Feature enhancement is already requested here - https://github.com/canonical/grafana-k8s-operator/issues/92

**Comment by hemanthnakkina** [comment]
@gboutry I am thinking to add your suggestion as separate PR which seems reasonable given its adding a new command.
I have submitted PR for grafana-k8s https://github.com/canonical/grafana-k8s-operator/pull/238

**Review by gboutry — APPROVED** [review]
Implementing as a second PR is reasonable, LGTM!

**Pull request merged**
